# Generated by Django 4.2.6 on 2023-10-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_short", models.TextField(max_length=255)),
                ("description_long", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/%y/%m/"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("price_marketing", models.FloatField(default=0)),
                ("price_marketing_promotional", models.FloatField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("V", "Variável"), ("S", "Simples")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="VariationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60, null=True)),
                ("price", models.FloatField()),
                ("price_promotional", models.FloatField(default=0)),
                ("stock", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variação do produto",
                "verbose_name_plural": "Variações dos produtos",
            },
        ),
    ]
