# Generated by Django 4.2.6 on 2023-10-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
