# Generated by Django 4.2.6 on 2023-10-22 19:38

import app.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=app.common.utils.ImageField(
                blank=True, null=True, upload_to="product_images/%y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
