# Generated by Django 4.2.6 on 2023-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_image_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_long",
            field=models.TextField(verbose_name="Descrição longa"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_short",
            field=models.TextField(max_length=255, verbose_name="Descrição curta"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_marketing",
            field=models.FloatField(default=0, verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_marketing_promotional",
            field=models.FloatField(default=0, verbose_name="Preço Promo."),
        ),
    ]
