# Generated by Django 4.2.6 on 2023-11-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemorder",
            old_name="product_name",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="itemorder",
            old_name="amount",
            new_name="quantity",
        ),
    ]
