# Generated by Django 4.2.6 on 2023-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="zip_code",
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
